<?php
if(isset($_POST['submit'])){
    ini_set('display_errors', 1);
    $so= $_POST['so_name'];
    $app_name= $_POST['app_name'];
    $desig = $_POST['desig'];
    $add = $_POST['add'];
    $thana=  $_POST['thana'];
    $district= $_POST['district'];
    $re_name= $_POST['re_name'];
    $re_desig= $_POST['re_desig'];
    $basic= $_POST['basic'];
    $house= $_POST['house'];
    $medical= $_POST['medical'];
    $allow= $_POST['allow'];
    $enter= $_POST['enter'];
    $others= $_POST['others'];
    $pro= $_POST['pro'];
    $date = date('d.m.Y');
    $total = $basic+$house+$medical+$allow+$enter+$others;

include('connect.php');
$ID = $_POST['submit'];
$sql = "SELECT * FROM employee WHERE `ID`='$ID'";
$res = mysqli_query($db, $sql);
$row = mysqli_fetch_assoc($res);
$fname = $row['First Name'];
$lname = $row['Last Name'];

$sql1 = "SELECT * FROM address WHERE `emp_id`='$ID'";
$res1 = mysqli_query($db, $sql1);
$row1 = mysqli_fetch_assoc($res1);
$vill = $row1['pre_village'];
$post_office = $row1['pre_post_office'];
$thanas = $row1['pre_thana'];
$districts = $row1['pre_district'];

$sql2 = "SELECT * FROM job_status WHERE `emp_id`='$ID'";
$res2 = mysqli_query($db, $sql2);
$row2 = mysqli_fetch_assoc($res2);
$des = $row2['curr_designation'];
$pros = $row2['probation_period'];
    
if($app_name=='')
    $app_name=$fname.' '.$lname;
if($desig=='')
    $desig=$des;
if($add=='')
    $add=$vill.' '.$post_office;
if($thana=='')
    $thana=$thanas;
if($district=='')
    $district=$districts;
if($pro=='')
    $pro=$pros;
    
require('fpdf/fpdf.php');
$pdf = new FPDF('P','mm','A4');
$pdf -> AddPage();
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(25);
$pdf -> Cell(30,10, 'SEL /HRD/Appointment/2018-ID', 0, 0);
$pdf -> Cell(110);
$pdf -> SetFont('Arial', '', 10);
$pdf -> Cell(0,10, 'Dated: '.$date);
$pdf -> Ln(10);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(0, 5, $app_name , 0, 1);
$pdf -> SetFont('Arial', '', 10);
$pdf -> Cell(8, 5, 'S/O: ', 0, 0);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(0, 5, $so , 0, 1);
$pdf -> Cell(0, 5, 'Permanent Address: ', 0, 1);
$pdf -> SetFont('Arial', '', 10);
$pdf -> Cell(0, 5, $add.',', 0, 1);
$pdf -> Cell(0, 5, $thana, 0, 1);
$pdf -> Cell(0, 5, $district, 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(0, 5, 'Subject: Letter of Employment Contract. ', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', '', 10);
$pdf -> Cell(9, 5, 'Dear ', 0, 0);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(0, 5, $app_name.',', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'With reference to your CV and subsequent interview with us, SEL Management is pleased to appoint you as ' .$desig. ' with effect from ' .$date .', under the following terms and conditions: ',0,1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'BU', 10);
$pdf -> Cell(0, 5, 'Terms and conditions:', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, '1. Work Station: Your workstation will be SEL Head Office, Uttara, Dhaka-1230, and you will be reporting to '.$re_name.', '.$re_desig.'. To further SEL\'s interest, you may be required to work anywhere in Bangladesh at management discretion. ', 0, 0);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, '2. Salary and Allowances: Your workstation will be '.$total.'. \The Break-down of your gross is appended below:', 0, 0);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', '', 8);
$pdf -> Cell(50);
$pdf -> Cell(60,4, 'Basic');
$pdf -> Cell(0,4, $basic ,0,1);
$pdf -> Cell(50);
$pdf -> Cell(60,4, 'House rent');
$pdf -> Cell(0,4, $house,0,1);
$pdf -> Cell(50);
$pdf -> Cell(60,4, 'Medical');
$pdf -> Cell(0,4, $medical ,0,1);
$pdf -> Cell(50);
$pdf -> Cell(60,4, 'Conveyance Allowance');
$pdf -> Cell(0,4, $allow ,0,1);
$pdf -> Cell(50);
$pdf -> Cell(60,4, 'Entertainment');
$pdf -> Cell(0,4, $allow ,0,1);
$pdf -> Cell(50);
$pdf -> Cell(60,4, 'Others');
$pdf -> Cell(0,3, $allow ,0,1);
$pdf -> Cell(50);
$pdf -> Cell(60,1, '-------------------------------------------------------------------------------',0,1);
$pdf -> Cell(50);
$pdf -> SetFont('Arial', 'B', 8);
$pdf -> Cell(60,3, 'Total Gross Salary: ',0,0);
$pdf -> Cell(0,4, $total ,0,1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(22, 5, '3. Probition: ', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'You will be on probation for a period of '. $pro. ' from the date of appointment. At the end of your', 0, 1);
$pdf -> MultiCell(0, 5, 'probation if your services are found to be satisfactory, your salary will be reviewed, and at the same time your appointment may be confirmed in writing as a permanent employee. The probation period may be extended for a further period not exceeding 03 months in case of necessity.', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(30, 5, '4. Hours of Work:', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'Generally, you will do 48 hours of work per week. The timing will be as below:', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'BU', 10);
$pdf -> Cell(0, 5, 'Office Hours ', 0, 1);
$pdf -> Ln(2);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(36, 5, 'Saturday - Thursday: ', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> Cell(0, 5, '9:00 am - 1:00 pm; & 2:00 pm - 6:00 pm (01:00 pm to 02:00 pm Lunch Break)', 0, 1);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(13, 5, 'Friday: ', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> Cell(0, 5, 'Weekly Holiday', 0, 1);
$pdf -> Cell(0, 5, 'However, for the benefit of SEL any additional voluntary hours that you may contribute would be appreciated. ', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(19, 5, '5. Caution:', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'You are not permitted to engage in other employment during your contract period with SEL. Any breach of', 0, 1);
$pdf -> MultiCell(0, 5, 'this provision will be ground for disciplinary action.', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(19, 5, '6. Leaves:', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'During the probationary period, you will not be entitled to the paid leave but, in case of medical ground it', 0, 1);
$pdf -> MultiCell(0, 5, 'could be relaxed. After confirmation, you will be entitled to enjoy leaves as per SEL policy.', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(40, 5, '7. Unauthorized Leave:', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'If you remain absent beyond the period of leave granted or extended, you shall be liable for', 0, 1);
$pdf -> MultiCell(0, 5, 'facing the disciplinary procedures as per Bangladesh labor law, unless you return within three days of expiry of leave and give a satisfactory explanation of your failure to return. Alternatively, at management\'s discretion, you may be suspended without salary for up to 7 days as a measure of necessary action.', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(26, 5, '8. Income Tax:', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'Officers/staffs who qualify for income tax payments SEL will deduct at source as required by law.', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(24, 5, '9. Discharge:', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'As per Bangladesh labor law, you may be discharged from service for reasons of physical or mental', 0, 1);
$pdf -> MultiCell(0, 5, 'incapacity or continued ill health.', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(25, 5, '10. Dismissal:', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'You may be dismissed as per Bangladesh labor law if: -', 0, 1);
$pdf -> Cell(3);
$pdf -> MultiCell(0, 5, 'a) You are convicted of any offence or moral turpitude', 0, 1);
$pdf -> Cell(3);
$pdf -> MultiCell(0, 5, 'b) SEL finds you guilty of misconduct.', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(28, 5, '11. Termination:', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'SEL at any time may discharge or terminate the service of a permanent employee by giving 1 (one) ', 0, 1);
$pdf -> MultiCell(0, 5, 'months\' notice or pay in lieu thereof.  ', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(28, 5, '12. Resignation:', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'You will be allowed to leave the job at SEL, but you must give minimum 01 (one) months\' notice or pay', 0, 1);
$pdf -> MultiCell(0, 5, 'in lieu thereof.', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(27, 5, '13. Bonus Pay:', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'As per the SEL policy, you will be entitled to festival bonus after serving one (01) year continuous', 0, 1);
$pdf -> MultiCell(0, 5, 'service at SEL. Two (02) festival bonus will be given in a fiscal year, and each festival bonus will be equivalent to half (50%) of one month’s gross salary.', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(22, 5, '14. Gratuity:', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'As per the SEL policy, you will be entitled to gratuity.', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(35, 5, '15. Provident Fund:', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'All full-time employees on confirmation shall become members of the Fund by an application in a', 0, 1);
$pdf -> MultiCell(0, 5, 'prescribed "Provident Fund" form and shall remain a member until the cessation of his employment. Each member contributes to the Fund BDT.100 up to 3 years from date of joining, and after 3 years 5% of his basic salary every month to which an equal amount will be added by SEL as the organization\'s contribution. If the member leaves the organization before/after completing 3 years of service from his date of joining will receive own part Plus organization part with profit/interest (if any).', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(6, 5, '16. ', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'As per the SEL policy, you will be entitled to Hospitalization benefit plan', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(20, 5, '17. Notice: ', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'Any notice of dismissal, discharge, or other termination may be given by serving a copy of the notice', 0, 1);
$pdf -> MultiCell(0, 5, 'personally on the employee or by posting to the employee\'s last known address and by posting a copy on SEL\'s Notice Board. ', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(47, 5, '18. Rules and Regulations: ', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'You will be bound to observe and to abide by SEL’s Rules and Regulations as ', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(36, 5, '19. Indemnity Bond: ', 0, 0);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'After confirmation of your service with SEL, you have to sign an indemnity bond to serve at SEL', 0, 1);
$pdf -> MultiCell(0, 5, 'at least 03 (three) continuous years of service.', 0, 1);
$pdf -> Ln(5);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'If you agree to the above terms and conditions, please return the duplicate copy of this letter to the undersigned with your signature thereon, signifying your acceptance thereof. ', 0, 1);
$pdf -> Ln(10);
$pdf -> MultiCell(0, 5, 'Thanking You.', 0, 1);
$pdf -> Ln(10);
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(0, 5, 'Syed Abu Jafar', 0, 1);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'Chairman, SEL', 0, 1);
$pdf -> AddPage();
$pdf -> SetFont('Arial', 'B', 10);
$pdf -> Cell(0, 5, 'Acceptance', 0, 1);
$pdf -> Ln(10);
$pdf -> SetFont('Arial', '', 10);
$pdf -> MultiCell(0, 5, 'I, ..................................................................................have read or have had translated and explained to me the above contract and I understand and agree to accept the terms and conditions as offered.', 0, 1);
$pdf -> Ln(10);
$pdf -> Cell(120, 5, 'Signature of employee........................',0,0);
$pdf -> Cell(0, 5, 'Date....................  ',0,1);
$pdf -> Cell(0,5, 'Time...................................',0,1);


$pdf -> output('I', 'appointment_letter.pdf');
}
else
   header("location:index.php");
?>